#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo ''
echo -e "\e[0;32m ******* pre-commit 钩子触发 **************\e[0m"
echo ''

node "D:/Study/Programming/Github/Turbo-LowCode/turbo-web/packages/lint/runLintStaged.mjs"
